#include <stdio.h>
#include <time.h>
#include <stdlib.h>


void printHelp(){
    printf(" ____________________________________________ \n");
    printf("|              Commands for Yukon            |\n");
    printf("|____________________________________________|\n");
    printf("|                                            |\n");
    printf("|                                            |\n");
    printf("|  How to start a game:                      |\n");
    printf("|  Load in a deck by using the               |\n");
    printf("|  command: LD                               |\n");
    printf("|  Before you start the game, it's recommend-|\n");
    printf("|  ed to shuffle the deck:                   |\n");
    printf("|  command: SR                               |\n");
    printf("|  To shuffle the deck.                      |\n");
    printf("|                                            |\n");
    printf("|  command: P                                |\n");
    printf("|  Starts the game, sets up all the cards.   |\n");
    printf("|                                            |\n");
    printf("|  How to move cards:                        |\n");
    printf("|  command: Cx:xx->Cx                        |\n");
    printf("|  example: C2:2H->C4                        |\n");
    printf("|  Moves the card 2H from column C2 to C4    |\n");
    printf("|  You can only move a single card at a time |\n");
    printf("|  if it is to the column for solved cards.  |\n");
    printf("|  In the example it is the 2 of Hearts      |\n");
    printf("|  that is moved to column 4 from column 2   |\n");
    printf("|  If you don't specify what card you're     |\n");
    printf("|  moving, C2->C4 for instance it will move  |\n");
    printf("|  the card at the bottom of your column.    |\n");
    printf("|                                            |\n");
    printf("|  command: Q                                |\n");
    printf("|  example: Quit game to \"main menu\"       |\n");
    printf("|                                            |\n");
    printf("|                                            |\n");
    printf("|  command: QQ                               |\n");
    printf("|  example: End program                      |\n");
    printf("|  Ends the game, program stops.             |\n");
    printf("|                                            |\n");
    printf("|____________________________________________|\n");
    printf("|                    Rules                   |\n");
    printf("|____________________________________________|\n");
    printf("|                                            |\n");
    printf("|  You have to move all cards into the       |\n");
    printf("|  solved column (C8)                        |\n");
    printf("|  You can only move the lowest card         |\n");
    printf("|  possible, from the start it's an Ace.     |\n");
    printf("|  You can only move the bottom card onto    |\n");
    printf("|  the solved piles                          |\n");
    printf("|  There are four piles, one for each color  |\n");
    printf("|  Hearts(H) Spades(S) Diamonds(D) Clubs(C)  |\n");
    printf("|                                            |\n");
    printf("|  You can free cards by moving the card     |\n");
    printf("|  above or multiple cards above.            |\n");
    printf("|  They can be moved to another pile (C1-C7) |\n");
    printf("|  but only if the number of the card        |\n");
    printf("|  that you are moving is one below the card |\n");
    printf("|  that you are moving it to.                |\n");
    printf("|  It also requires that the color is not    |\n");
    printf("|  the same as the card you are moving       |\n");
    printf("|  meant as they cannot both be spades or    |\n");
    printf("|  or both be hearts but if one of them is   |\n");
    printf("|  spades then the other one can be clubs    |\n");
    printf("|                                            |\n");
    printf("|  Moving a card with cards below it also    |\n");
    printf("|  moves all the cards below regardless of   |\n");
    printf("|  their number or color                     |\n");
    printf("|  If you move cards away from a card that   |\n");
    printf("|  is face down ([]) then that card is       |\n");
    printf("|  flipped and is now in play as well        |\n");
    printf("|  There are one of each card and there are  |\n");
    printf("|  no duplicates.                            |\n");
    printf("|                                            |\n");
    printf("|  To win, all cards must be flipped and     |\n");
    printf("|  moved to the four foundations             |\n");
    printf("|____________________________________________|\n");
}